# Generated by Django 6.0 on 2025-12-23 18:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forum", "0002_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="attachment",
            field=models.FileField(blank=True, null=True, upload_to="comments/files/"),
        ),
        migrations.AddField(
            model_name="comment",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="comments/images/"
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="attachment",
            field=models.FileField(blank=True, null=True, upload_to="posts/files/"),
        ),
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="posts/images/"),
        ),
    ]
