# Generated by Django 6.0 on 2025-12-23 19:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forum", "0003_comment_attachment_comment_image_post_attachment_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="attachment",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="image",
        ),
        migrations.RemoveField(
            model_name="post",
            name="attachment",
        ),
        migrations.RemoveField(
            model_name="post",
            name="image",
        ),
        migrations.AddField(
            model_name="comment",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="comments/"),
        ),
        migrations.AddField(
            model_name="post",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="posts/"),
        ),
    ]
